C:\VulkanSDK\1.4.341.1\Bin\glslc.exe vert.vert -o vert.spv
C:\VulkanSDK\1.4.341.1\Bin\glslc.exe diffuse.frag -o diffuse.spv
C:\VulkanSDK\1.4.341.1\Bin\glslc.exe pbr.frag -o pbr.spv
C:\VulkanSDK\1.4.341.1\Bin\glslc.exe composition.frag -o composition.spv
C:\VulkanSDK\1.4.341.1\Bin\glslc.exe quad.vert -o quad.spv
C:\VulkanSDK\1.4.341.1\Bin\glslc.exe ssao.frag -o ssao.spv
C:\VulkanSDK\1.4.341.1\Bin\glslc.exe ssao_blur.frag -o ssao_blur.spv
C:\VulkanSDK\1.4.341.1\Bin\glslc.exe post_process.frag -o post_process.spv
C:\VulkanSDK\1.4.341.1\Bin\glslc.exe bloom.frag -o bloom.spv
C:\VulkanSDK\1.4.341.1\Bin\glslc.exe shadows.geom -o shadows_geom.spv
C:\VulkanSDK\1.4.341.1\Bin\glslc.exe rtx.frag -o rtx.spv
C:\VulkanSDK\1.4.341.1\Bin\glslc.exe rtx_denoiser.frag -o rtx_denoiser.spv
